// Hardcoded translations — no API needed

export const translations: Record<string, { vi: string; en: string }> = {
  // Sidebar menu
  'Thống Kê': { vi: 'Thống Kê', en: 'Statistics' },
  'Kế Hoạch': { vi: 'Kế Hoạch', en: 'Planning' },
  'Dự Án': { vi: 'Dự Án', en: 'Projects' },
  'Giao Nhận': { vi: 'Giao Nhận', en: 'Delivery' },
  'Kiểm Hàng': { vi: 'Kiểm Hàng', en: 'QC' },
  'Quét QR': { vi: 'Quét QR', en: 'QR Scan' },
  'Đóng Gói': { vi: 'Đóng Gói', en: 'Packing' },
  'Lên Hàng': { vi: 'Lên Hàng', en: 'Loading' },
  'Kho Hàng': { vi: 'Kho Hàng', en: 'Inventory' },
  'Nhân Sự': { vi: 'Nhân Sự', en: 'Staff' },
  'Khách Hàng': { vi: 'Khách Hàng', en: 'Customers' },
  'Tài Khoản': { vi: 'Tài Khoản', en: 'Accounts' },
  'Khách': { vi: 'Khách', en: 'Guest' },
  'Khách hàng': { vi: 'Khách hàng', en: 'Customer' },
  'Mở rộng': { vi: 'Mở rộng', en: 'Extensions' },
  'Trạm In': { vi: 'Trạm In', en: 'Print Station' },
  'Bảng Điều Khiển': { vi: 'Bảng Điều Khiển', en: 'Dashboard' },

  // Common
  'Đăng xuất': { vi: 'Đăng xuất', en: 'Logout' },
  'Đăng nhập': { vi: 'Đăng nhập', en: 'Login' },
  'Đăng nhập với Google': { vi: 'Đăng nhập với Google', en: 'Sign in with Google' },
  'Đang tải...': { vi: 'Đang tải...', en: 'Loading...' },
  'Đang đăng nhập...': { vi: 'Đang đăng nhập...', en: 'Signing in...' },
  'Lỗi': { vi: 'Lỗi', en: 'Error' },
  'Không có dữ liệu': { vi: 'Không có dữ liệu', en: 'No data' },
  'Xem': { vi: 'Xem', en: 'View' },
  'Thêm': { vi: 'Thêm', en: 'Add' },
  'Chia sẻ': { vi: 'Chia sẻ', en: 'Share' },
  'Trở về': { vi: 'Trở về', en: 'Back' },
  'Cài đặt': { vi: 'Cài đặt', en: 'Settings' },
  'Tiếng Việt': { vi: 'Tiếng Việt', en: 'Vietnamese' },
  'English': { vi: 'Tiếng Anh', en: 'English' },
  'Tìm kiếm': { vi: 'Tìm kiếm', en: 'Search' },
  'Thông tin cá nhân': { vi: 'Thông tin cá nhân', en: 'Profile' },
  'Họ & Tên thật': { vi: 'Họ & Tên thật', en: 'Full Name' },
  'Chức danh / Vị trí': { vi: 'Chức danh / Vị trí', en: 'Title / Position' },
  'Lưu thông tin': { vi: 'Lưu thông tin', en: 'Save Info' },
  'Thoát': { vi: 'Thoát', en: 'Logout' },
  'Xác nhận thoát tài khoản?': { vi: 'Xác nhận thoát tài khoản?', en: 'Confirm logout?' },
  'Đồng ý': { vi: 'Đồng ý', en: 'Confirm' },
  'Bạn đang đăng nhập với tư cách khách hàng. Nhấn nút "Thoát" bên dưới để đăng xuất.': { vi: 'Bạn đang đăng nhập với tư cách khách hàng. Nhấn nút "Thoát" bên dưới để đăng xuất.', en: 'You are signed in as a customer. Click "Logout" below to sign out.' },
  'Hệ Thống DRACO-X2': { vi: 'Hệ Thống DRACO-X2', en: 'DRACO-X2 System' },
  'Hệ Thống Quản Lý & QC Hàng Chờ': { vi: 'Hệ Thống Quản Lý & QC Hàng Chờ', en: 'Management & QC System' },
  'Vui lòng nhập ID và mật khẩu được cấp để truy cập hệ thống.': { vi: 'Vui lòng nhập ID và mật khẩu được cấp để truy cập hệ thống.', en: 'Please enter your ID and password to access the system.' },
  'ID Đăng Nhập': { vi: 'ID Đăng Nhập', en: 'Login ID' },
  'Nhập ID': { vi: 'Nhập ID', en: 'Enter ID' },
  'Mật Khẩu': { vi: 'Mật Khẩu', en: 'Password' },
  'Nhập mật khẩu': { vi: 'Nhập mật khẩu', en: 'Enter password' },
  'Đăng nhập thất bại. Vui lòng thử lại.': { vi: 'Đăng nhập thất bại. Vui lòng thử lại.', en: 'Login failed. Please try again.' },
  'ID không tồn tại.': { vi: 'ID không tồn tại.', en: 'ID does not exist.' },
  'Mật khẩu không đúng.': { vi: 'Mật khẩu không đúng.', en: 'Incorrect password.' },
  'Anonymous Auth chưa được bật. Vui lòng bật trong Firebase Console > Authentication > Sign-in method > Anonymous.': { vi: 'Anonymous Auth chưa được bật. Vui lòng bật trong Firebase Console > Authentication > Sign-in method > Anonymous.', en: 'Anonymous Auth is not enabled. Please enable it in Firebase Console > Authentication > Sign-in method > Anonymous.' },
  'Chào mừng bạn quay trở lại. Vui lòng đăng nhập bằng tài khoản Google để truy cập bảng điều khiển và trực tiếp cập nhật dữ liệu dự án.': { vi: 'Chào mừng bạn quay trở lại. Vui lòng đăng nhập bằng tài khoản Google để truy cập bảng điều khiển và trực tiếp cập nhật dữ liệu dự án.', en: 'Welcome back. Please sign in with Google to access the dashboard and update project data.' },
  'Thông tin hệ thống': { vi: 'Thông tin hệ thống', en: 'System Info' },
  'Hệ thống tự động lưu trữ nhật ký hoạt động sản xuất, kiểm định chất lượng (QC) và phân hệ bàn giao lưu trữ trực tiếp trên cơ sở dữ liệu đám mây.': { vi: 'Hệ thống tự động lưu trữ nhật ký hoạt động sản xuất, kiểm định chất lượng (QC) và phân hệ bàn giao lưu trữ trực tiếp trên cơ sở dữ liệu đám mây.', en: 'The system automatically stores production logs, quality control (QC) records, and delivery management directly on cloud database.' },
  'Thêm mới': { vi: 'Thêm mới', en: 'Add New' },
  'Sửa': { vi: 'Sửa', en: 'Edit' },
  'Xóa': { vi: 'Xóa', en: 'Delete' },
  'Lưu': { vi: 'Lưu', en: 'Save' },
  'Hủy': { vi: 'Hủy', en: 'Cancel' },
  'Đóng': { vi: 'Đóng', en: 'Close' },
  'Xác nhận': { vi: 'Xác nhận', en: 'Confirm' },
  'Tất cả': { vi: 'Tất cả', en: 'All' },
  'Trạng thái': { vi: 'Trạng thái', en: 'Status' },
  'Cụm': { vi: 'Cụm', en: 'Cluster' },
  'Mã Module': { vi: 'Mã Module', en: 'Module Code' },
  'Số lượng': { vi: 'Số lượng', en: 'Quantity' },
  'Đã nhận': { vi: 'Đã nhận', en: 'Received' },
  'Chưa nhận': { vi: 'Chưa nhận', en: 'Pending' },
  'Đã đóng gói': { vi: 'Đã đóng gói', en: 'Packed' },
  'Dự án': { vi: 'Dự án', en: 'Project' },
  'Danh sách': { vi: 'Danh sách', en: 'List' },
  'Lọc': { vi: 'Lọc', en: 'Filter' },
  'Tổng': { vi: 'Tổng', en: 'Total' },
  'Không tên': { vi: 'Không tên', en: 'Untitled' },
  'Ghi chú': { vi: 'Ghi chú', en: 'Notes' },
  'Tạo': { vi: 'Tạo', en: 'Create' },
  'Chọn': { vi: 'Chọn', en: 'Select' },
  'Bỏ chọn': { vi: 'Bỏ chọn', en: 'Deselect' },
  'Hoàn tất': { vi: 'Hoàn tất', en: 'Complete' },
  'Chưa hoàn tất': { vi: 'Chưa hoàn tất', en: 'Incomplete' },
  'Đang xử lý': { vi: 'Đang xử lý', en: 'Processing' },
  'Không tìm thấy': { vi: 'Không tìm thấy', en: 'Not found' },
  'Xác nhận xóa?': { vi: 'Xác nhận xóa?', en: 'Confirm delete?' },
  'Bạn có chắc chắn muốn xóa': { vi: 'Bạn có chắc chắn muốn xóa', en: 'Are you sure you want to delete' },
  'Đồng ý xóa': { vi: 'Đồng ý xóa', en: 'Confirm delete' },
  'Huỷ bỏ': { vi: 'Huỷ bỏ', en: 'Cancel' },
  'Đang tải ảnh lên...': { vi: 'Đang tải ảnh lên...', en: 'Uploading...' },
  'Đang xử lý...': { vi: 'Đang xử lý...', en: 'Processing...' },

  // Project Management
  'Danh sách Module': { vi: 'Danh sách Module', en: 'Module List' },
  'Chi tiết cấu kiện': { vi: 'Chi tiết cấu kiện', en: 'Component Details' },
  'Mô hình 3D (CAD ISO View)': { vi: 'Mô hình 3D (CAD ISO View)', en: '3D Model (CAD ISO View)' },
  'Mã': { vi: 'Mã', en: 'Code' },
  'Loại': { vi: 'Loại', en: 'Type' },
  'Nhận': { vi: 'Nhận', en: 'Received' },
  'D×R×C': { vi: 'D×R×C', en: 'L×W×H' },
  'Vật liệu': { vi: 'Vật liệu', en: 'Material' },
  'QC từng kiện': { vi: 'QC từng kiện', en: 'QC per piece' },
  'Kiện': { vi: 'Kiện', en: 'Piece' },
  'Ảnh': { vi: 'Ảnh', en: 'Photos' },
  'Vật tư phụ': { vi: 'Vật tư phụ', en: 'Accessories' },
  'Nhật ký': { vi: 'Nhật ký', en: 'History' },
  'Chọn cấu kiện': { vi: 'Chọn cấu kiện', en: 'Select component' },
  'bên trái để xem thông tin': { vi: 'bên trái để xem thông tin', en: 'on the left to view details' },
  'Tổng số Module': { vi: 'Tổng số Module', en: 'Total Modules' },
  'Phân loại': { vi: 'Phân loại', en: 'Classification' },
  'Toàn bộ Cụm': { vi: 'Toàn bộ Cụm', en: 'All Clusters' },
  'Thùng & Cấu kiện con': { vi: 'Thùng & Cấu kiện con', en: 'Boxes & Components' },
  'CTHT': { vi: 'CTHT', en: 'CTHT' },
  'Len, Filler, Filter': { vi: 'Len, Filler, Filter', en: 'Len, Filler, Filter' },
  'Phụ Kiện': { vi: 'Phụ Kiện', en: 'Accessories' },
  'Không có phụ kiện nào trong dự án': { vi: 'Không có phụ kiện nào trong dự án', en: 'No accessories in this project' },
  'Cập nhật': { vi: 'Cập nhật', en: 'Update' },
  'Đang sắp xếp lại thứ tự dự án...': { vi: 'Đang sắp xếp lại thứ tự dự án...', en: 'Reordering projects...' },
  'CỤM': { vi: 'CỤM', en: 'CLUSTER' },
  'TRẠNG THÁI': { vi: 'TRẠNG THÁI', en: 'STATUS' },
  'In tem tạm cho cấu kiện dạng Thùng': { vi: 'In tem tạm cho cấu kiện dạng Thùng', en: 'Print temp label for box components' },
  'Tạo link chia sẻ dự án cho khách': { vi: 'Tạo link chia sẻ dự án cho khách', en: 'Create share link for guests' },
  'Chỉnh sửa chi tiết module dự án dưới dạng bảng Excel': { vi: 'Chỉnh sửa chi tiết module dự án dưới dạng bảng Excel', en: 'Edit project module details in Excel format' },
  'Bỏ đánh dấu hoàn tất': { vi: 'Bỏ đánh dấu hoàn tất', en: 'Unmark complete' },
  'Đánh dấu hoàn tất dự án': { vi: 'Đánh dấu hoàn tất dự án', en: 'Mark project complete' },
  'Xóa dự án': { vi: 'Xóa dự án', en: 'Delete project' },
  'Ẩn bớt các cấu kiện con': { vi: 'Ẩn bớt các cấu kiện con', en: 'Hide child components' },
  'Hiện tất cả cấu kiện con': { vi: 'Hiện tất cả cấu kiện con', en: 'Show all child components' },
  'Đề nghị xuất hàng phụ kiện': { vi: 'Đề nghị xuất hàng phụ kiện', en: 'Request accessory export' },
  'Thêm phụ kiện mới': { vi: 'Thêm phụ kiện mới', en: 'Add new accessory' },
  'Kéo thả để sắp xếp': { vi: 'Kéo thả để sắp xếp', en: 'Drag to reorder' },
  'HOÀN TẤT': { vi: 'HOÀN TẤT', en: 'DONE' },
  'Chưa có dự án nào': { vi: 'Chưa có dự án nào', en: 'No projects yet' },
  'Mô hình 3D': { vi: 'Mô hình 3D', en: '3D Model' },
  'Bản vẽ PDF': { vi: 'Bản vẽ PDF', en: 'PDF Drawing' },
  'In Tem Tạm': { vi: 'In Tem Tạm', en: 'Print Temp Label' },
  'Chỉnh Excel': { vi: 'Chỉnh Excel', en: 'Edit Excel' },
  'Sửa Dự Án': { vi: 'Sửa Dự Án', en: 'Edit Project' },
  'Đã nhận đủ': { vi: 'Đã nhận đủ', en: 'Fully received' },
  'Đang nhận chưa đủ': { vi: 'Đang nhận chưa đủ', en: 'Partially received' },
  'QC Pass': { vi: 'QC Pass', en: 'QC Pass' },
  'Nhận X2': { vi: 'Nhận X2', en: 'Received X2' },
  'SL': { vi: 'SL', en: 'Qty' },
  'QC': { vi: 'QC', en: 'QC' },
  'Dự Án Sản Xuất': { vi: 'Dự Án Sản Xuất', en: 'Production Projects' },
  'Hệ thống quản lý sản xuất Xưởng 2': { vi: 'Hệ thống quản lý sản xuất Xưởng 2', en: 'Workshop 2 Production Management' },
  'Dự án đã hoàn tất': { vi: 'Dự án đã hoàn tất', en: 'Completed projects' },
  'Tiến độ nhận hàng': { vi: 'Tiến độ nhận hàng', en: 'Receiving progress' },
  'Món': { vi: 'Món', en: 'items' },
  'Chi Tiết Dự Án': { vi: 'Chi Tiết Dự Án', en: 'Project Details' },
  'loại': { vi: 'loại', en: 'types' },
  'Hạng mục phụ kiện': { vi: 'Hạng mục phụ kiện', en: 'Accessory items' },
  'Đã chọn': { vi: 'Đã chọn', en: 'Selected' },
  'Cấu kiện con: Hiện': { vi: 'Cấu kiện con: Hiện', en: 'Children: Shown' },
  'Cấu kiện con: Ẩn': { vi: 'Cấu kiện con: Ẩn', en: 'Children: Hidden' },
  'Ghép Nhanh': { vi: 'Ghép Nhanh', en: 'Quick Group' },
  'Hủy chọn': { vi: 'Hủy chọn', en: 'Cancel selection' },
  'Chọn xóa': { vi: 'Chọn xóa', en: 'Select to delete' },
  'Tổng hợp Phụ Kiện công trình': { vi: 'Tổng hợp Phụ Kiện công trình', en: 'Project Accessories Summary' },
  'Đề nghị xuất': { vi: 'Đề nghị xuất', en: 'Request export' },
  'Tên Phụ Kiện': { vi: 'Tên Phụ Kiện', en: 'Accessory Name' },
  'Đã Xuất / Tổng': { vi: 'Đã Xuất / Tổng', en: 'Exported / Total' },
  'Chưa xuất kho': { vi: 'Chưa xuất kho', en: 'Not exported' },
  'Không có phụ kiện': { vi: 'Không có phụ kiện', en: 'No accessories' },
  'Check Đợt di động': { vi: 'Check Đợt di động', en: 'Check Mobile Shelf' },
  'Đánh dấu các đợt di động...': { vi: 'Đánh dấu các đợt di động...', en: 'Marking mobile shelves...' },
  'Không tìm thấy đợt di động nào...': { vi: 'Không tìm thấy đợt di động nào...', en: 'No mobile shelves found...' },
  'Thùng:': { vi: 'Thùng:', en: 'Box:' },
  'Đợt:': { vi: 'Đợt:', en: 'Shelf:' },
  'Số lượng đợt:': { vi: 'Số lượng đợt:', en: 'Shelf qty:' },
  'Nhận đủ': { vi: 'Nhận đủ', en: 'Received' },
  'Đánh dấu các đợt di động có đủ số lượng của module thùng tương ứng.': { vi: 'Đánh dấu các đợt di động có đủ số lượng của module thùng tương ứng.', en: 'Mark mobile shelves that have sufficient quantity for the corresponding box module.' },
  'Kiểm xong': { vi: 'Kiểm xong', en: 'QC done' },
  'Kiểm lại': { vi: 'Kiểm lại', en: 'Re-check' },
  'Dự án:': { vi: 'Dự án:', en: 'Project:' },
  'Hiện tại:': { vi: 'Hiện tại:', en: 'Current:' },

  // Packing
  'Phiếu đóng gói': { vi: 'Phiếu đóng gói', en: 'Packing List' },
  'Tạo phiếu': { vi: 'Tạo phiếu', en: 'Create List' },
  'TẠO MỚI': { vi: 'TẠO MỚI', en: 'CREATE NEW' },
  'Thêm kiện': { vi: 'Thêm kiện', en: 'Add Item' },
  'Xóa kiện': { vi: 'Xóa kiện', en: 'Remove Item' },
  'Danh sách Packing': { vi: 'Danh sách Packing', en: 'Packing List' },
  'Tên đóng gói': { vi: 'Tên đóng gói', en: 'List Name' },
  'Tiến độ': { vi: 'Tiến độ', en: 'Progress' },
  'Hoàn thành': { vi: 'Hoàn thành', en: 'Completed' },
  'Chưa có Packing List': { vi: 'Chưa có Packing List', en: 'No packing lists yet' },
  'Chưa có đóng gói nào': { vi: 'Chưa có đóng gói nào', en: 'No packing data yet' },
  'Tạo Phiếu Đóng Gói': { vi: 'Tạo Phiếu Đóng Gói', en: 'Create Packing List' },
  'Thiết lập theo dự án': { vi: 'Thiết lập theo dự án', en: 'Setup by project' },
  'Nhập dữ liệu thủ công': { vi: 'Nhập dữ liệu thủ công', en: 'Manual input' },
  'Vào dự án': { vi: 'Vào dự án', en: 'Project' },
  '-- CHỌN DỰ ÁN --': { vi: '-- CHỌN DỰ ÁN --', en: '-- SELECT PROJECT --' },
  'Mô tả đóng gói': { vi: 'Mô tả đóng gói', en: 'Packing description' },
  'Quay lại': { vi: 'Quay lại', en: 'Go back' },
  'Xác nhận khởi tạo': { vi: 'Xác nhận khởi tạo', en: 'Confirm create' },
  'Chi Tiết Đóng Gói': { vi: 'Chi Tiết Đóng Gói', en: 'Packing Details' },
  'Tìm Module hoặc Khu vực...': { vi: 'Tìm Module hoặc Khu vực...', en: 'Search Module or Area...' },
  'Quét Mã': { vi: 'Quét Mã', en: 'Scan QR' },
  'Quét Lên Xe': { vi: 'Quét Lên Xe', en: 'Scan to Load' },
  'Kiện Module': { vi: 'Kiện Module', en: 'Module Items' },
  'Kiện CTHT': { vi: 'Kiện CTHT', en: 'CTHT Items' },
  'Kiện PK': { vi: 'Kiện PK', en: 'Accessory Items' },
  'Thông tin chung': { vi: 'Thông tin chung', en: 'General Info' },
  'Tiến độ tổng': { vi: 'Tiến độ tổng', en: 'Overall Progress' },
  'KIỆN ĐÃ ĐÓNG': { vi: 'KIỆN ĐÃ ĐÓNG', en: 'PACKED ITEMS' },
  'TIẾN ĐỘ LÊN XE': { vi: 'TIẾN ĐỘ LÊN XE', en: 'LOAD PROGRESS' },
  'Mã dự án': { vi: 'Mã dự án', en: 'Project Code' },
  'Tên dự án': { vi: 'Tên dự án', en: 'Project Name' },
  'Đóng Phụ Kiện': { vi: 'Đóng Phụ Kiện', en: 'Pack Accessories' },
  'Đóng CTHT': { vi: 'Đóng CTHT', en: 'Pack CTHT' },
  'Sửa nhanh dạng Excel': { vi: 'Sửa nhanh dạng Excel', en: 'Quick Edit Excel' },
  'In tem thùng': { vi: 'In tem thùng', en: 'Print box label' },
  'Hoàn tất toàn bộ List': { vi: 'Hoàn tất toàn bộ List', en: 'Complete entire list' },
  'Đồng bộ': { vi: 'Đồng bộ', en: 'Sync' },
  'Xoá': { vi: 'Xoá', en: 'Delete' },
  'Đã Đóng Gói': { vi: 'Đã Đóng Gói', en: 'Packed' },
  'Xác nhận bởi:': { vi: 'Xác nhận bởi:', en: 'Confirmed by:' },
  'Hình ảnh thực tế': { vi: 'Hình ảnh thực tế', en: 'Actual photos' },
  'Ảnh Sản phẩm': { vi: 'Ảnh Sản phẩm', en: 'Product photos' },
  'Ảnh đóng gói': { vi: 'Ảnh đóng gói', en: 'Packing photos' },
  'Chưa có ảnh nào': { vi: 'Chưa có ảnh nào', en: 'No photos yet' },
  'Đã gửi in': { vi: 'Đã gửi in', en: 'Sent to print' },
  'In tem': { vi: 'In tem', en: 'Print label' },
  'Lưu Nháp & Thoát': { vi: 'Lưu Nháp & Thoát', en: 'Save Draft & Exit' },
  'Xác nhận hoàn tất': { vi: 'Xác nhận hoàn tất', en: 'Confirm complete' },
  'Xác nhận lên xe?': { vi: 'Xác nhận lên xe?', en: 'Confirm loading?' },
  'Bỏ qua': { vi: 'Bỏ qua', en: 'Skip' },
  'Lên xe ngay': { vi: 'Lên xe ngay', en: 'Load now' },
  'Số lượng: ': { vi: 'Số lượng: ', en: 'Quantity: ' },
  'Tạo Kiện Phụ Kiện': { vi: 'Tạo Kiện Phụ Kiện', en: 'Create Accessory Item' },
  'Tạo Kiện CTHT': { vi: 'Tạo Kiện CTHT', en: 'Create CTHT Item' },
  'In Tem Ngay': { vi: 'In Tem Ngay', en: 'Print Now' },
  '← Quay lại danh sách dự án': { vi: '← Quay lại danh sách dự án', en: '← Back to project list' },
  'Xác nhận xoá?': { vi: 'Xác nhận xoá?', en: 'Confirm delete?' },
  'Đồng ý xoá': { vi: 'Đồng ý xoá', en: 'Confirm delete' },
  'Đã hiểu': { vi: 'Đã hiểu', en: 'Got it' },
  'Không có phiếu nào khác': { vi: 'Không có phiếu nào khác', en: 'No other lists' },
  'Tên Kiện': { vi: 'Tên Kiện', en: 'Item Name' },
  'Chỉnh tên module': { vi: 'Chỉnh tên module', en: 'Edit Module Names' },
  'Tên module': { vi: 'Tên module', en: 'Module Name' },
  'Tên hiển thị': { vi: 'Tên hiển thị', en: 'Display Name' },
  'Tên object': { vi: 'Tên object', en: 'Object Name' },
  'Tên cụm object': { vi: 'Tên cụm object', en: 'Object Cluster Name' },
  'Tên module gốc — không thể chỉnh sửa': { vi: 'Tên module gốc — không thể chỉnh sửa', en: 'Original module name — read only' },
  'Hiển thị thay cho tên module trong danh sách module': { vi: 'Hiển thị thay cho tên module trong danh sách module', en: 'Shown instead of the module name in the module list' },
  'Dùng để khớp object trong mô hình 3D, thay cho mã module': { vi: 'Dùng để khớp object trong mô hình 3D, thay cho mã module', en: 'Used to match objects in the 3D model, replacing the module code' },
  'Dùng để khớp object 3D theo cụm, thay cho tên cụm gốc': { vi: 'Dùng để khớp object 3D theo cụm, thay cho tên cụm gốc', en: 'Used to match 3D objects by cluster, replacing the original cluster name' },
  'Kích thước': { vi: 'Kích thước', en: 'Dimensions' },
  'Cân (Kg)': { vi: 'Cân (Kg)', en: 'Weight (Kg)' },
  '1 căn (CODE)': { vi: '1 căn (CODE)', en: '1 unit (CODE)' },
  'Nhiều căn (UNIT)': { vi: 'Nhiều căn (UNIT)', en: 'Multiple units (UNIT)' },
  'Huỷ Trạng Thái': { vi: 'Huỷ Trạng Thái', en: 'Cancel Status' },
  'CHƯA ĐỦ ĐIỀU KIỆN': { vi: 'CHƯA ĐỦ ĐIỀU KIỆN', en: 'REQUIREMENTS NOT MET' },
  'Ảnh xác nhận đóng gói (Tối thiểu 3 ảnh)': { vi: 'Ảnh xác nhận đóng gói (Tối thiểu 3 ảnh)', en: 'Packing confirmation photos (Min 3 photos)' },
  'Xóa hết ảnh': { vi: 'Xóa hết ảnh', en: 'Delete all photos' },
  'Thêm / Thay đổi ảnh (Chọn từ 3 ảnh)': { vi: 'Thêm / Thay đổi ảnh (Chọn từ 3 ảnh)', en: 'Add / Change photos (Select up to 3)' },
  'Chụp / Chọn ảnh đóng gói (Tối thiểu 3 ảnh)': { vi: 'Chụp / Chọn ảnh đóng gói (Tối thiểu 3 ảnh)', en: 'Capture / Select packing photos (Min 3)' },
  'Phụ kiện kèm theo (Đã xác nhận)': { vi: 'Phụ kiện kèm theo (Đã xác nhận)', en: 'Accessories (Confirmed)' },
  'Chi tiết FINISHED PANEL': { vi: 'Chi tiết FINISHED PANEL', en: 'FINISHED PANEL details' },
  'Sửa tên kiện CTHT': { vi: 'Sửa tên kiện CTHT', en: 'Edit CTHT item name' },
  'Sửa tên dự án': { vi: 'Sửa tên dự án', en: 'Edit project name' },
  'Nhập tên dự án (ví dụ: Dự án A)': { vi: 'Nhập tên dự án (ví dụ: Dự án A)', en: 'Enter project name (e.g. Project A)' },
  'Bấm vào ảnh để xem kích thước đầy đủ & chuyển đổi trước/sau': { vi: '* Bấm vào ảnh để xem kích thước đầy đủ & chuyển đổi trước/sau', en: '* Click photo to view full size & navigate' },
  'Đang tải dự án': { vi: 'Đang tải dự án', en: 'Loading projects' },
  'Tiến độ Lên Xe': { vi: 'Tiến độ Lên Xe', en: 'Loading Progress' },
  'KIỆN ĐÃ LÊN XE': { vi: 'KIỆN ĐÃ LÊN XE', en: 'LOADED ITEMS' },
  'Kiện Phụ Kiện': { vi: 'Kiện Phụ Kiện', en: 'Accessory Items' },

  // Loading
  'Quản lý phiếu xếp hàng (PKL)': { vi: 'Quản lý phiếu xếp hàng (PKL)', en: 'Loading list management (PKL)' },
  'Tạo PKL Mới': { vi: 'Tạo PKL Mới', en: 'Create New PKL' },
  'Tìm module theo tên để biết đang ở xe nào...': { vi: 'Tìm module theo tên để biết đang ở xe nào...', en: 'Search module name to find which vehicle...' },
  'Chưa có phiếu PKL nào': { vi: 'Chưa có phiếu PKL nào', en: 'No loading lists yet' },
  'Danh Sách Packing List (PKL)': { vi: 'Danh Sách Packing List (PKL)', en: 'Loading List (PKL)' },
  'Tên Đợt Hàng': { vi: 'Tên Đợt Hàng', en: 'Batch Name' },
  'Mã PKL': { vi: 'Mã PKL', en: 'PKL Code' },
  'Phương Tiện': { vi: 'Phương Tiện', en: 'Vehicle' },
  'Số lượng bốc': { vi: 'Số lượng bốc', en: 'Loaded qty' },
  'Người lập': { vi: 'Người lập', en: 'Created by' },
  'Kiện bốc': { vi: 'Kiện bốc', en: 'Loaded items' },
  'Tạo Phiếu Lên Hàng (PKL)': { vi: 'Tạo Phiếu Lên Hàng (PKL)', en: 'Create Loading List (PKL)' },
  'Chọn Dự Án': { vi: 'Chọn Dự Án', en: 'Select Project' },
  '-- LIÊN DỰ ÁN (XẾP XE NHIỀU DỰ ÁN) --': { vi: '-- LIÊN DỰ ÁN (XẾP XE NHIỀU DỰ ÁN) --', en: '-- MULTI-PROJECT (LOAD MULTIPLE) --' },
  'Thông Tin Xe Vận Chuyển': { vi: 'Thông Tin Xe Vận Chuyển', en: 'Vehicle Info' },
  'Ghi Chú': { vi: 'Ghi Chú', en: 'Notes' },
  'HỦY': { vi: 'HỦY', en: 'CANCEL' },
  'XÁC NHẬN': { vi: 'XÁC NHẬN', en: 'CONFIRM' },
  'Sửa Thông Tin Phiếu Lên Hàng': { vi: 'Sửa Thông Tin Phiếu Lên Hàng', en: 'Edit Loading List Info' },
  'Mã Dự Án Trong Phiếu': { vi: 'Mã Dự Án Trong Phiếu', en: 'Project Codes in List' },
  'Thông tin xe:': { vi: 'Thông tin xe:', en: 'Vehicle:' },
  'Chưa cập nhật': { vi: 'Chưa cập nhật', en: 'Not updated' },
  'Dự án chính:': { vi: 'Dự án chính:', en: 'Main project:' },
  'Tổng kiện bốc:': { vi: 'Tổng kiện bốc:', en: 'Total loaded:' },
  'Ngày tạo phiếu:': { vi: 'Ngày tạo phiếu:', en: 'Created:' },
  'Đang mở': { vi: 'Đang mở', en: 'Open' },
  'Đã đóng': { vi: 'Đã đóng', en: 'Closed' },
  'Chưa có': { vi: 'Chưa có', en: 'None' },
  'Đọc tất cả': { vi: 'Đọc tất cả', en: 'Read all' },
  'Không có thông báo nào dành cho bạn': { vi: 'Không có thông báo nào dành cho bạn', en: 'No notifications for you' },

  // Project List Table
  'Nhóm': { vi: 'Nhóm', en: 'Group' },
  'Tiến độ nhận': { vi: 'Tiến độ nhận', en: 'Receive progress' },
  'Danh sách Dự Án': { vi: 'Danh sách Dự Án', en: 'Project List' },
  'Chưa có Dự Án': { vi: 'Chưa có Dự Án', en: 'No projects yet' },
  'MODULE': { vi: 'MODULE', en: 'MODULE' },
  'Cá nhân': { vi: 'Cá nhân', en: 'Personal' },
  'KIỆN GÓI': { vi: 'KIỆN GÓI', en: 'PACKED' },

  // ModuleDetailModal
  'Mã số định danh': { vi: 'Mã số định danh', en: 'Identification Number' },
  'Thông tin truy xuất': { vi: 'Thông tin truy xuất', en: 'Traceability Info' },
  'Mã QR Không Thuộc Dự Án': { vi: 'Mã QR Không Thuộc Dự Án', en: 'QR Code Not in Project' },
  'Thông tin cấu kiện cơ bản': { vi: 'Thông tin cấu kiện cơ bản', en: 'Basic Component Info' },
  'Cụm / Khu vực': { vi: 'Cụm / Khu vực', en: 'Cluster / Area' },
  'Kích thước (D x R x C)': { vi: 'Kích thước (D x R x C)', en: 'Dimensions (L x W x H)' },
  'Kích thước (D x R x C) (mm)': { vi: 'Kích thước (D x R x C) (mm)', en: 'Dimensions (L x W x H) (mm)' },
  'Kích thước (D x R x C) (in)': { vi: 'Kích thước (D x R x C) (in)', en: 'Dimensions (L x W x H) (in)' },
  'Tiến độ Giao Nhận dự án': { vi: 'Tiến độ Giao Nhận dự án', en: 'Project Delivery Progress' },
  'Chưa phân cụm': { vi: 'Chưa phân cụm', en: 'Unclustered' },
  'Không xác định': { vi: 'Không xác định', en: 'Undefined' },
  'Mô hình 3D cấu kiện (CAD ISO View)': { vi: 'Mô hình 3D cấu kiện (CAD ISO View)', en: '3D Model (CAD ISO View)' },
  'Hình ảnh ngoại quan thực tế': { vi: 'Hình ảnh ngoại quan thực tế', en: 'Actual External Photos' },
  'Tình trạng QC từng kiện': { vi: 'Tình trạng QC từng kiện', en: 'QC Status per Piece' },
  'Chờ': { vi: 'Chờ', en: 'Pending' },
  'Thông tin lên hàng': { vi: 'Thông tin lên hàng', en: 'Loading Info' },
  'Thời gian': { vi: 'Thời gian', en: 'Time' },
  'Người xếp': { vi: 'Người xếp', en: 'Loaded by' },
  'Phương tiện': { vi: 'Phương tiện', en: 'Vehicle' },
  'Danh sách cấu kiện con': { vi: 'Danh sách cấu kiện con', en: 'Child Components' },
  'Cấu kiện con': { vi: 'Cấu kiện con', en: 'Child Component' },
  'Phụ kiện đi kèm': { vi: 'Phụ kiện đi kèm', en: 'Accessories' },
  'Nhật ký lịch sử cấu kiện': { vi: 'Nhật ký lịch sử cấu kiện', en: 'Component History' },
  'Không có lịch sử': { vi: 'Không có lịch sử', en: 'No history' },
  'Hệ thống chưa ghi nhận các hoạt động thay đổi cấu kiện này.': { vi: 'Hệ thống chưa ghi nhận các hoạt động thay đổi cấu kiện này.', en: 'No changes recorded for this component.' },
  'Đóng cửa sổ': { vi: 'Đóng cửa sổ', en: 'Close window' },
  'Biểu mẫu Chỉnh sửa cấu kiện': { vi: 'Biểu mẫu Chỉnh sửa cấu kiện', en: 'Edit Component Form' },
  'Mã cấu kiện': { vi: 'Mã cấu kiện', en: 'Component Code' },
  'Kích thước Thiết kế (Rộng x Sâu x Cao) (mm)': { vi: 'Kích thước Thiết kế (Rộng x Sâu x Cao) (mm)', en: 'Design Dimensions (W x D x H) (mm)' },
  'Kích thước Sản xuất (pWidth x pDepth x pHeight) (mm)': { vi: 'Kích thước Sản xuất (pWidth x pDepth x pHeight) (mm)', en: 'Production Dimensions (pWidth x pDepth x pHeight) (mm)' },
  'Số lượng (Tổng)': { vi: 'Số lượng (Tổng)', en: 'Quantity (Total)' },
  'Số lượng lắp ráp': { vi: 'Số lượng lắp ráp', en: 'Assembly Quantity' },
  'Tầng / Khu vực (Area)': { vi: 'Tầng / Khu vực (Area)', en: 'Floor / Area' },
  'Đơn vị / Block (Unit)': { vi: 'Đơn vị / Block (Unit)', en: 'Unit / Block' },
  'Link Bản vẽ chi tiết (PDF/Hình ảnh/...)': { vi: 'Link Bản vẽ chi tiết (PDF/Hình ảnh/...)', en: 'Detail Drawing Link (PDF/Image/...)' },
  'Link Bản vẽ lắp ráp (PDF/Hình ảnh/...)': { vi: 'Link Bản vẽ lắp ráp (PDF/Hình ảnh/...)', en: 'Assembly Drawing Link (PDF/Image/...)' },
  'Đường dẫn Mô hình 3D (.glb)': { vi: 'Đường dẫn Mô hình 3D (.glb)', en: '3D Model Path (.glb)' },
  'Ghi nhận thay đổi': { vi: 'Ghi nhận thay đổi', en: 'Save Changes' },

  // ProjectManagementScreen — alerts & confirms
  'Bạn có chắc chắn muốn sắp xếp lại tất cả các module con theo đúng module thùng cha?': { vi: 'Bạn có chắc chắn muốn sắp xếp lại tất cả các module con theo đúng module thùng cha?', en: 'Are you sure you want to reorder all child modules to match their parent cabinet module?' },
  'Đã sắp xếp lại và lưu thứ tự thành công!': { vi: 'Đã sắp xếp lại và lưu thứ tự thành công!', en: 'Reordered and saved successfully!' },
  'Không thể cập nhật thứ tự dự án': { vi: 'Không thể cập nhật thứ tự dự án', en: 'Cannot update project order' },
  'Bỏ đánh dấu hoàn tất dự án': { vi: 'Bỏ đánh dấu hoàn tất dự án', en: 'Unmark project as complete' },
  'Dự án sẽ quay lại danh sách hoạt động.': { vi: 'Dự án sẽ quay lại danh sách hoạt động.', en: 'The project will return to the active list.' },
  'Đánh dấu dự án': { vi: 'Đánh dấu dự án', en: 'Mark project' },
  'là': { vi: 'là', en: 'as' },
  'Dự án sẽ được ẩn khỏi thống kê và xếp xuống cuối danh sách.': { vi: 'Dự án sẽ được ẩn khỏi thống kê và xếp xuống cuối danh sách.', en: 'The project will be hidden from statistics and moved to the bottom of the list.' },
  'Không thể cập nhật trạng thái dự án. Vui lòng thử lại.': { vi: 'Không thể cập nhật trạng thái dự án. Vui lòng thử lại.', en: 'Cannot update project status. Please try again.' },
  'Lỗi lưu kết quả kiểm đợt di động': { vi: 'Lỗi lưu kết quả kiểm đợt di động', en: 'Error saving shelf check results' },
  'Chỉnh tên hiển thị & tên object 3D': { vi: 'Chỉnh tên hiển thị & tên object 3D', en: 'Edit display name & 3D object name' },
  'Xem Raw Data': { vi: 'Xem Raw Data', en: 'View Raw Data' },
  'Không tìm thấy đợt di động nào tương ứng với các module thùng của dự án này.': { vi: 'Không tìm thấy đợt di động nào tương ứng với các module thùng của dự án này.', en: 'No matching shelves found for cabinet modules in this project.' },
  'Khi bấm': { vi: 'Khi bấm', en: 'When pressing' },
  'những đợt được check sẽ chuyển sang trạng thái': { vi: 'những đợt được check sẽ chuyển sang trạng thái', en: 'the checked shelves will change to status' },
  'và ghi nhận đủ số lượng. Đợt không được check sẽ đổi thành trạng thái': { vi: 'và ghi nhận đủ số lượng. Đợt không được check sẽ đổi thành trạng thái', en: 'and the quantity will be recorded as complete. Unchecked shelves will change to status' },
  'Chưa có trạng thái': { vi: 'Chưa có trạng thái', en: 'No status' },
  'Trắng': { vi: 'Trắng', en: 'White' },
  'Sơn': { vi: 'Sơn', en: 'Paint' },
  'Gói': { vi: 'Gói', en: 'Pack' },
  'Đóng gói': { vi: 'Đóng gói', en: 'Packing' },
  'Đã sắp xếp lại thứ tự dự án...': { vi: 'Đã sắp xếp lại thứ tự dự án...', en: 'Reordering projects...' },
};
